server {
    listen 8012;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location = /script.js {
        try_files $uri =404;
    }

    location = /style.css {
        try_files $uri =404;
    }

    location /assets/ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
